// Code generated by Kitex v0.12.1. DO NOT EDIT.

package userservice

import (
	"context"
	user "github.com/123508/douyinshop/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, Req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error)
	Login(ctx context.Context, Req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	Logout(ctx context.Context, Req *user.LogoutReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	GetUserInfo(ctx context.Context, Req *user.GetUserInfoReq, callOptions ...callopt.Option) (r *user.GetUserInfoResp, err error)
	Update(ctx context.Context, Req *user.UpdateReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	Delete(ctx context.Context, Req *user.DeleteReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	ListUsers(ctx context.Context, Req *user.ListUsersReq, callOptions ...callopt.Option) (r *user.ListUsersResp, err error)
	DeliverTokenByRPC(ctx context.Context, Req *user.DeliverTokenReq, callOptions ...callopt.Option) (r *user.DeliveryResp, err error)
	VerifyTokenByRPC(ctx context.Context, Req *user.VerifyTokenReq, callOptions ...callopt.Option) (r *user.VerifyResp, err error)
	ChangePassword(ctx context.Context, Req *user.ChangePasswordReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	ForgotPassword(ctx context.Context, Req *user.ForgotPasswordReq, callOptions ...callopt.Option) (r *user.ForgotPasswordResp, err error)
	VerifySmsCode(ctx context.Context, Req *user.VerifySmsCodeReq, callOptions ...callopt.Option) (r *user.VerifySmsCodeResp, err error)
	ResetPassword(ctx context.Context, Req *user.ResetPasswordReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	PreBindEmail(ctx context.Context, Req *user.PreBindEmailReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	BindEmail(ctx context.Context, Req *user.BindEmailReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	PreUnbindEmail(ctx context.Context, Req *user.PreUnbindEmailReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	UnbindEmail(ctx context.Context, Req *user.UnbindEmailReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	PreFreezeUser(ctx context.Context, Req *user.PreFreezeUserReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	FreezeUser(ctx context.Context, Req *user.FreezeUserReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	PreUnfreezeUser(ctx context.Context, Req *user.PreUnFreezeUserReq, callOptions ...callopt.Option) (r *user.Empty, err error)
	UnfreezeUser(ctx context.Context, Req *user.UnfreezeUserReq, callOptions ...callopt.Option) (r *user.Empty, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, Req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kUserServiceClient) Login(ctx context.Context, Req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kUserServiceClient) Logout(ctx context.Context, Req *user.LogoutReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, Req)
}

func (p *kUserServiceClient) GetUserInfo(ctx context.Context, Req *user.GetUserInfoReq, callOptions ...callopt.Option) (r *user.GetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, Req)
}

func (p *kUserServiceClient) Update(ctx context.Context, Req *user.UpdateReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Update(ctx, Req)
}

func (p *kUserServiceClient) Delete(ctx context.Context, Req *user.DeleteReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, Req)
}

func (p *kUserServiceClient) ListUsers(ctx context.Context, Req *user.ListUsersReq, callOptions ...callopt.Option) (r *user.ListUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUsers(ctx, Req)
}

func (p *kUserServiceClient) DeliverTokenByRPC(ctx context.Context, Req *user.DeliverTokenReq, callOptions ...callopt.Option) (r *user.DeliveryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeliverTokenByRPC(ctx, Req)
}

func (p *kUserServiceClient) VerifyTokenByRPC(ctx context.Context, Req *user.VerifyTokenReq, callOptions ...callopt.Option) (r *user.VerifyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyTokenByRPC(ctx, Req)
}

func (p *kUserServiceClient) ChangePassword(ctx context.Context, Req *user.ChangePasswordReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePassword(ctx, Req)
}

func (p *kUserServiceClient) ForgotPassword(ctx context.Context, Req *user.ForgotPasswordReq, callOptions ...callopt.Option) (r *user.ForgotPasswordResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ForgotPassword(ctx, Req)
}

func (p *kUserServiceClient) VerifySmsCode(ctx context.Context, Req *user.VerifySmsCodeReq, callOptions ...callopt.Option) (r *user.VerifySmsCodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifySmsCode(ctx, Req)
}

func (p *kUserServiceClient) ResetPassword(ctx context.Context, Req *user.ResetPasswordReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResetPassword(ctx, Req)
}

func (p *kUserServiceClient) PreBindEmail(ctx context.Context, Req *user.PreBindEmailReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreBindEmail(ctx, Req)
}

func (p *kUserServiceClient) BindEmail(ctx context.Context, Req *user.BindEmailReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindEmail(ctx, Req)
}

func (p *kUserServiceClient) PreUnbindEmail(ctx context.Context, Req *user.PreUnbindEmailReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreUnbindEmail(ctx, Req)
}

func (p *kUserServiceClient) UnbindEmail(ctx context.Context, Req *user.UnbindEmailReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnbindEmail(ctx, Req)
}

func (p *kUserServiceClient) PreFreezeUser(ctx context.Context, Req *user.PreFreezeUserReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreFreezeUser(ctx, Req)
}

func (p *kUserServiceClient) FreezeUser(ctx context.Context, Req *user.FreezeUserReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FreezeUser(ctx, Req)
}

func (p *kUserServiceClient) PreUnfreezeUser(ctx context.Context, Req *user.PreUnFreezeUserReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreUnfreezeUser(ctx, Req)
}

func (p *kUserServiceClient) UnfreezeUser(ctx context.Context, Req *user.UnfreezeUserReq, callOptions ...callopt.Option) (r *user.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnfreezeUser(ctx, Req)
}
