// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: bitjump_address.proto

package address

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreetAddress string `protobuf:"bytes,1,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"` // 详细地址
	City          string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`                                        // 城市
	State         string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                                      // 省份/州
	Country       string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`                                  // 国家
	ZipCode       int32  `protobuf:"varint,5,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`                  // 邮编
	Consignee     string `protobuf:"bytes,6,opt,name=consignee,proto3" json:"consignee,omitempty"`                              // 收货人
	Gender        []byte `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`                                    // 性别 1:男 0:女
	Phone         string `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`                                      // 电话
	Label         string `protobuf:"bytes,9,opt,name=Label,proto3" json:"Label,omitempty"`                                      // 标签
	IsDefault     bool   `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`           // 是否默认地址
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

func (x *Address) GetConsignee() string {
	if x != nil {
		return x.Consignee
	}
	return ""
}

func (x *Address) GetGender() []byte {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *Address) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Address) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Address) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type AddressItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddrId  uint64   `protobuf:"varint,1,opt,name=addr_id,json=addrId,proto3" json:"addr_id,omitempty"` // 地址ID
	Address *Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AddressItem) Reset() {
	*x = AddressItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressItem) ProtoMessage() {}

func (x *AddressItem) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressItem.ProtoReflect.Descriptor instead.
func (*AddressItem) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{1}
}

func (x *AddressItem) GetAddrId() uint64 {
	if x != nil {
		return x.AddrId
	}
	return 0
}

func (x *AddressItem) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type AddAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Address *Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AddAddressReq) Reset() {
	*x = AddAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressReq) ProtoMessage() {}

func (x *AddAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressReq.ProtoReflect.Descriptor instead.
func (*AddAddressReq) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{2}
}

func (x *AddAddressReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddAddressReq) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type AddAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddrId uint64 `protobuf:"varint,1,opt,name=addr_id,json=addrId,proto3" json:"addr_id,omitempty"`
}

func (x *AddAddressResp) Reset() {
	*x = AddAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressResp) ProtoMessage() {}

func (x *AddAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressResp.ProtoReflect.Descriptor instead.
func (*AddAddressResp) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{3}
}

func (x *AddAddressResp) GetAddrId() uint64 {
	if x != nil {
		return x.AddrId
	}
	return 0
}

type GetAddressListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAddressListReq) Reset() {
	*x = GetAddressListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddressListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressListReq) ProtoMessage() {}

func (x *GetAddressListReq) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressListReq.ProtoReflect.Descriptor instead.
func (*GetAddressListReq) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{4}
}

func (x *GetAddressListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAddressListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []*AddressItem `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
}

func (x *GetAddressListResp) Reset() {
	*x = GetAddressListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddressListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressListResp) ProtoMessage() {}

func (x *GetAddressListResp) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressListResp.ProtoReflect.Descriptor instead.
func (*GetAddressListResp) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{5}
}

func (x *GetAddressListResp) GetAddress() []*AddressItem {
	if x != nil {
		return x.Address
	}
	return nil
}

type DeleteAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddrId uint64 `protobuf:"varint,2,opt,name=addr_id,json=addrId,proto3" json:"addr_id,omitempty"`
}

func (x *DeleteAddressReq) Reset() {
	*x = DeleteAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressReq) ProtoMessage() {}

func (x *DeleteAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressReq.ProtoReflect.Descriptor instead.
func (*DeleteAddressReq) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAddressReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteAddressReq) GetAddrId() uint64 {
	if x != nil {
		return x.AddrId
	}
	return 0
}

type DeleteAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *DeleteAddressResp) Reset() {
	*x = DeleteAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResp) ProtoMessage() {}

func (x *DeleteAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResp.ProtoReflect.Descriptor instead.
func (*DeleteAddressResp) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAddressResp) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type UpdateAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddrId  uint64   `protobuf:"varint,2,opt,name=addr_id,json=addrId,proto3" json:"addr_id,omitempty"`
	Address *Address `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *UpdateAddressReq) Reset() {
	*x = UpdateAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressReq) ProtoMessage() {}

func (x *UpdateAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressReq.ProtoReflect.Descriptor instead.
func (*UpdateAddressReq) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAddressReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAddressReq) GetAddrId() uint64 {
	if x != nil {
		return x.AddrId
	}
	return 0
}

func (x *UpdateAddressReq) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type UpdateAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *UpdateAddressResp) Reset() {
	*x = UpdateAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressResp) ProtoMessage() {}

func (x *UpdateAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressResp.ProtoReflect.Descriptor instead.
func (*UpdateAddressResp) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAddressResp) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type SetDefaultAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddrId uint64 `protobuf:"varint,2,opt,name=addr_id,json=addrId,proto3" json:"addr_id,omitempty"`
}

func (x *SetDefaultAddressReq) Reset() {
	*x = SetDefaultAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultAddressReq) ProtoMessage() {}

func (x *SetDefaultAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultAddressReq.ProtoReflect.Descriptor instead.
func (*SetDefaultAddressReq) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{10}
}

func (x *SetDefaultAddressReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetDefaultAddressReq) GetAddrId() uint64 {
	if x != nil {
		return x.AddrId
	}
	return 0
}

type SetDefaultAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *SetDefaultAddressResp) Reset() {
	*x = SetDefaultAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bitjump_address_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultAddressResp) ProtoMessage() {}

func (x *SetDefaultAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_bitjump_address_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultAddressResp.ProtoReflect.Descriptor instead.
func (*SetDefaultAddressResp) Descriptor() ([]byte, []int) {
	return file_bitjump_address_proto_rawDescGZIP(), []int{11}
}

func (x *SetDefaultAddressResp) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

var File_bitjump_address_proto protoreflect.FileDescriptor

var file_bitjump_address_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x69, 0x74, 0x6a, 0x75, 0x6d, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x90, 0x02, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x22, 0x52, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x64, 0x64, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x54, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x29, 0x0a,
	0x0e, 0x41, 0x64, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x17, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x61, 0x64, 0x64, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x44, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x64, 0x64, 0x72,
	0x49, 0x64, 0x22, 0x25, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x70, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x64, 0x64, 0x72, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x25, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72,
	0x65, 0x73, 0x22, 0x48, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x64, 0x64, 0x72, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x15,
	0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x32, 0x88, 0x03, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x11,
	0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1d, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x1e, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x31, 0x32, 0x33, 0x35, 0x30, 0x38, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x73, 0x68,
	0x6f, 0x70, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bitjump_address_proto_rawDescOnce sync.Once
	file_bitjump_address_proto_rawDescData = file_bitjump_address_proto_rawDesc
)

func file_bitjump_address_proto_rawDescGZIP() []byte {
	file_bitjump_address_proto_rawDescOnce.Do(func() {
		file_bitjump_address_proto_rawDescData = protoimpl.X.CompressGZIP(file_bitjump_address_proto_rawDescData)
	})
	return file_bitjump_address_proto_rawDescData
}

var file_bitjump_address_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_bitjump_address_proto_goTypes = []interface{}{
	(*Address)(nil),               // 0: address.Address
	(*AddressItem)(nil),           // 1: address.AddressItem
	(*AddAddressReq)(nil),         // 2: address.AddAddressReq
	(*AddAddressResp)(nil),        // 3: address.AddAddressResp
	(*GetAddressListReq)(nil),     // 4: address.GetAddressListReq
	(*GetAddressListResp)(nil),    // 5: address.GetAddressListResp
	(*DeleteAddressReq)(nil),      // 6: address.DeleteAddressReq
	(*DeleteAddressResp)(nil),     // 7: address.DeleteAddressResp
	(*UpdateAddressReq)(nil),      // 8: address.UpdateAddressReq
	(*UpdateAddressResp)(nil),     // 9: address.UpdateAddressResp
	(*SetDefaultAddressReq)(nil),  // 10: address.SetDefaultAddressReq
	(*SetDefaultAddressResp)(nil), // 11: address.SetDefaultAddressResp
}
var file_bitjump_address_proto_depIdxs = []int32{
	0,  // 0: address.AddressItem.address:type_name -> address.Address
	0,  // 1: address.AddAddressReq.address:type_name -> address.Address
	1,  // 2: address.GetAddressListResp.address:type_name -> address.AddressItem
	0,  // 3: address.UpdateAddressReq.address:type_name -> address.Address
	2,  // 4: address.AddressService.AddAddress:input_type -> address.AddAddressReq
	4,  // 5: address.AddressService.GetAddressList:input_type -> address.GetAddressListReq
	6,  // 6: address.AddressService.DeleteAddress:input_type -> address.DeleteAddressReq
	8,  // 7: address.AddressService.UpdateAddress:input_type -> address.UpdateAddressReq
	10, // 8: address.AddressService.SetDefaultAddress:input_type -> address.SetDefaultAddressReq
	3,  // 9: address.AddressService.AddAddress:output_type -> address.AddAddressResp
	5,  // 10: address.AddressService.GetAddressList:output_type -> address.GetAddressListResp
	7,  // 11: address.AddressService.DeleteAddress:output_type -> address.DeleteAddressResp
	9,  // 12: address.AddressService.UpdateAddress:output_type -> address.UpdateAddressResp
	11, // 13: address.AddressService.SetDefaultAddress:output_type -> address.SetDefaultAddressResp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bitjump_address_proto_init() }
func file_bitjump_address_proto_init() {
	if File_bitjump_address_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bitjump_address_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddressListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddressListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bitjump_address_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bitjump_address_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bitjump_address_proto_goTypes,
		DependencyIndexes: file_bitjump_address_proto_depIdxs,
		MessageInfos:      file_bitjump_address_proto_msgTypes,
	}.Build()
	File_bitjump_address_proto = out.File
	file_bitjump_address_proto_rawDesc = nil
	file_bitjump_address_proto_goTypes = nil
	file_bitjump_address_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.12.1. DO NOT EDIT.

type AddressService interface {
	AddAddress(ctx context.Context, req *AddAddressReq) (res *AddAddressResp, err error)
	GetAddressList(ctx context.Context, req *GetAddressListReq) (res *GetAddressListResp, err error)
	DeleteAddress(ctx context.Context, req *DeleteAddressReq) (res *DeleteAddressResp, err error)
	UpdateAddress(ctx context.Context, req *UpdateAddressReq) (res *UpdateAddressResp, err error)
	SetDefaultAddress(ctx context.Context, req *SetDefaultAddressReq) (res *SetDefaultAddressResp, err error)
}
