version: "3"

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=bitjump
      - MYSQL_USER=bitjump
      - MYSQL_PASSWORD=bitjump
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./deploy/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    privileged: true
  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./deploy/etcd/data:/bitnami/etcd-data
    environment:
      - TZ=Asia/Shanghai
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ROOT_PASSWORD=bitjump
  elasticsearch:
    container_name: es01
    image: elasticsearch:8.12.2
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "TZ=Asia/Shanghai"
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=123456"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./deploy/els/config:/usr/share/elasticsearch/config
      - ./deploy/els/data:/usr/share/elasticsearch/data
      - ./deploy/els/plugins:/usr/share/elasticsearch/plugins
