mysql:
  host: 127.0.0.1
  port: 3306
  user: "bitjump"
  password: "bitjump"
  dbname: "bitjump"
  max_open_conns: 20
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100

jwt:
  # 设置jwt签名加密时使用的秘钥
  admin_secret_key: "your admin_secret_key"
  # 设置jwt过期时间为7天
  admin_ttl: 604800
  admin_suv: 10800

elasticsearch:
  hosts:
    - "http://127.0.0.1:9200"
  username: ""
  password: ""

etcd:
  endpoints: 127.0.0.1:2379
  username: ""
  password: ""

hertz:
  host: 127.0.0.1
  port: 8900

auth:
  host: 127.0.0.1
  port: 8901
  service_name: "bitjump.douyinshop.auth"

user:
  host: 127.0.0.1
  port: 8902
  service_name: "bitjump.douyinshop.user"

cart:
  host: 127.0.0.1
  port: 8903
  service_name: "bitjump.douyinshop.cart"

checkout:
  host: 127.0.0.1
  port: 8904
  service_name: "bitjump.douyinshop.checkout"

order:
  host: 127.0.0.1
  port: 8905
  service_name: "bitjump.douyinshop.order"

payment:
  host: 127.0.0.1
  port: 8906
  service_name: "bitjump.douyinshop.payment"
  alipay:
    app_id: "your app_id"
    app_private_key: "your app_private_key"

product:
  host: 127.0.0.1
  port: 8907
  service_name: "bitjump.douyinshop.product"

address:
  host: 127.0.0.1
  port: 8908
  service_name: "bitjump.douyinshop.address"

business_order:
  host: 127.0.0.1
  port: 8909
  service_name: "bitjump.douyinshop.business_order"

shop:
  host: 127.0.0.1
  port: 8910
  service_name: "bitjump.douyinshop.shop"

ai:
  host: 127.0.0.1
  port: 8911
  service_name: "bitjump.douyinshop.ai"
  timeout: 30s

volcengine:
  api_key: "your api_key"  # 从火山引擎控制台获取
  douyin_model: "DeepSeek-R1-Distill-Qwen-32B"  # 使用的模型版本
  timeout: 30  # 超时时间（秒）
  max_tokens: 2048  # 最大token数
  retry_times: 3  # 
aliyun:
  uploadPath: 1 #1上传到本地服务器,2上传到AliOss服务器
  oss:
    endpoint: "your endpoint"
    accessKeyId: "your accessKeyId"
    accessKeySecret: "your accessKeySecret"
    bucketName: "your bucketName"


rabbitmq:
  host: 127.0.0.1 #主机名
  port: 5672 #端口
  virtual_host: "/" #虚拟主机
  username: "your username" #用户名
  password: "your password" #密码
  prefetch: 1 #每次只能获取一条消息,处理完后才能获取下一个消息

logger:
  level: "error" # 设置日志级别为error
  output: "./log.txt" # 输出到标准错误，也可以设置为文件路径
