mysql:
  host: 127.0.0.1
  port: 3306
  user: "bitjump"
  password: "bitjump"
  dbname: "bitjump"
  max_open_conns: 20
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100

etcd:
  endpoints: 127.0.0.1:2379
  username: "root"
  password: "bitjump"

jwt:
  # 设置jwt签名加密时使用的秘钥
  admin_secret_key: "ThisServiceIsOfferedByBitJump"
  # 设置jwt过期时间为7天
  admin_ttl: 604800
  # 令牌存活时间低于该时间令牌自动刷新
  admin_suv: 10800

elasticsearch:
  hosts:
    - "http://127.0.0.1:9200"
  username: "elastic"
  password: "123456"

hertz:
  host: 127.0.0.1
  port: 8900

auth:
  host: 127.0.0.1
  port: 8901
  service_name: "bitjump.douyinshop.auth"

user:
  host: 127.0.0.1
  port: 8902
  service_name: "bitjump.douyinshop.user"

cart:
  host: 127.0.0.1
  port: 8903
  service_name: "bitjump.douyinshop.cart"

checkout:
  host: 127.0.0.1
  port: 8904
  service_name: "bitjump.douyinshop.checkout"

order:
  host: 127.0.0.1
  port: 8905
  service_name: "bitjump.douyinshop.order"

payment:
  host: 127.0.0.1
  port: 8906
  service_name: "bitjump.douyinshop.payment"

product:
  host: 127.0.0.1
  port: 8907
  service_name: "bitjump.douyinshop.product"

address:
  host: 127.0.0.1
  port: 8908
  service_name: "bitjump.douyinshop.address"

business_order:
  host: 127.0.0.1
  port: 8909
  service_name: "bitjump.douyinshop.business_order"

shop:
  host: 127.0.0.1
  port: 8910
  service_name: "bitjump.douyinshop.shop"

ai:
  host: 127.0.0.1
  port: 8911
  service_name: "bitjump.douyinshop.ai"


aliyun:
  oss:
    endpoint: "your endpoint"
    accessKeyId: "your accessKeyId"
    accessKeySecret: "your accessKeySecret"
    bucketName: "your bucketName"